### ISSUE TITLE
Code - Code Script - Generate  -> Expected type 'int', got 'str' instead

### ISSUE THREAD

**Issue by matecsaj** [alejandroautalan/pygubu-designer#114]
sample output

> self.consider_item_description.grid(column="0", columnspan="2", row="3")
> self.window_pained.add(self.frame2, weight="1")
>

The keyword arguments should be integers instead of strings.

**Comment by jrezai** [comment]
I don't think it will affect the usability when strings are used instead of integers.

When Tkinter expects a number (ie: row=3), it still works fine with row="3" given as a string.
I believe the reason it's fine with strings when it's expecting a number is because Tkinter uses TCL under the hood, and apparently in TCL [everything is a string](https://wiki.tcl-lang.org/page/everything+is+a+string).

I'm not a TCL expert by any stretch, but that seems to be the most logical explanation I can think of as to why Tkinter works fine with integers and also strings.

**Comment by rdbende** [comment]
Yes, it works just fine with strings, because Tkinter translates **every** object to string under the hood anyway.
But it's just more Pythonic to use integers instead of string everywhere.

**Comment by alejandroautalan** [comment]
Hello all, thanks for the comments.
I change it to be more pythonic. It will be available in the next release.

Regards.
Alejandro A.
