### ISSUE TITLE
Class PhotoImage

### ISSUE THREAD

**Issue by vlotho** [alejandroautalan/pygubu-designer#16]
Hi,

I have not found, for the moment, any gui offering the PhotoImage class.

**Comment by alejandroautalan** [comment]
Hello vlotho thanks for trying pygubu.

> I have not found, for the moment, any gui offering the PhotoImage class.

Maybe it's because an image is just one element that a widget can have.
If you only want to show a static image, you can use a Label and associate an image with it.
Here is an example of a [static image](https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/static_image) with pygubu. And another more advanced with an [image on a canvas](https://github.com/alejandroautalan/pygubu-designer/tree/master/examples/jpg_image_on_canvas). Other example [here](https://github.com/alejandroautalan/pygubu/wiki/ImageProperty) .

Let me know if this helps you.

Regards
Alejandro A.
